import { Router, Request, Response } from 'express';
import { v4 as uuid } from 'uuid';
import { loadStore, saveStore } from '../lib/persistence';
import { parseCsv } from '../lib/csv';
import { organizations } from './organizations';
import { damaRoles, DAMA_ROLE_TYPES } from './dama-roles';
import { governanceGroups } from './governance-groups';
import { processNodes } from './process-catalog';
import { dataAssets } from './data-assets';
import { dataDomains } from './data-domains';
import logger from '../lib/logger';

const ROLES = [
  'SUPER_ADMIN',
  'ORG_ADMIN',
  'EDITOR',
  'CONTRIBUTOR',
  'VIEWER',
] as const;

export interface StoredPerson {
  id: string;
  orgIds: string[];
  accessibleOrgIds: string[];
  name: string;
  email: string;
  role: string;
  title: string;
  jobRole?: string;
  skillIds: string[];
  /** Argon2id hash of the user's local password. Only present when
   *  the Local auth provider has been set up for this person. OIDC /
   *  SAML / Dev users never carry a hash — login federates to the IdP
   *  or skips credentials entirely. The hash MUST be stripped from
   *  every API response that surfaces a person record; see
   *  publicPerson() below. */
  passwordHash?: string;
  /** ISO timestamp of the last password change. Drives audit + the
   *  forced-rotation check on first login after an admin reset. */
  passwordUpdatedAt?: string;
  /** When true, the user's current password was set by an admin or
   *  the dev→local migration and must be changed before the user can
   *  do anything else. The login flow short-circuits to a "set new
   *  password" prompt instead of issuing a normal session. */
  passwordMustChange?: boolean;
  /** Base32-encoded TOTP secret. Present once the user has scanned
   *  the QR and verified a code; absent before enrollment and after
   *  disable / admin-reset. SHOULD be encrypted at rest in
   *  production — Argon2 doesn't apply (the server has to compute
   *  HMAC against the raw bytes), so this needs a column-level KMS
   *  layer when Postgres lands. Stripped from every API response
   *  via publicPerson(). */
  mfaSecret?: string;
  /** True once enrollment is verified end-to-end (the user proved
   *  they can produce a code from the secret). The login flow checks
   *  this flag, not just presence of mfaSecret, so partial enrollment
   *  doesn't lock a user out. */
  mfaEnrolled?: boolean;
  /** Argon2id hashes of single-use backup codes. Generated at
   *  enrollment, shown to the user once, hashed for storage. Removed
   *  on use; regenerated by an admin reset. */
  mfaBackupCodes?: string[];
  /** Registered WebAuthn / FIDO2 credentials. A user can have many
   *  — a YubiKey, a phone fingerprint, a laptop's platform key.
   *  Either WebAuthn OR TOTP satisfies the MFA gate at login; users
   *  can configure both. credentialID and publicKey are base64url
   *  binary; counter is the per-credential replay counter the
   *  authenticator increments on each use. */
  webauthnCredentials?: Array<{
    id: string;             // internal handle (uuid)
    credentialID: string;   // base64url, returned by the authenticator
    publicKey: string;      // base64url, COSE-encoded
    counter: number;        // replay counter, expected to monotonically increase
    transports?: string[];  // e.g. ['internal','hybrid','usb']
    label: string;          // user-supplied: "YubiKey 5", "iPhone Touch ID"
    createdAt: string;
  }>;
  /** Soft-delete flag. Absent or true → the person can sign in and
   *  appears in default list views. False → the person is preserved
   *  for audit but cannot authenticate, doesn't appear in default
   *  lists, and is exposed to SCIM as active=false. Set by SCIM PUT /
   *  PATCH with active=false (the standard offboarding signal IdPs
   *  send) and by the admin "Deactivate" action. Reactivation just
   *  flips the flag back. SCIM DELETE still hard-deletes — explicit
   *  is explicit. */
  active?: boolean;
  /** Timestamp of the active=false transition. Lets the People page
   *  show "Deactivated 12 days ago" and audit reports surface
   *  recently-disabled accounts. */
  deactivatedAt?: string;
  createdAt: string;
  updatedAt: string;
}

/** A person is "active" when the flag is absent OR true. Existing
 *  records predate the field; treating absence as active is the
 *  only safe back-compat read. */
export function isActive(p: StoredPerson): boolean {
  return p.active !== false;
}

/** Strip credential fields from a person record before sending over
 *  the wire. Every read path that returns people MUST use this; the
 *  raw StoredPerson is internal-only.
 *
 *  Strips:
 *    - passwordHash         the Argon2 password hash
 *    - mfaSecret            the TOTP secret (HMAC key — server-side
 *                           only)
 *    - mfaBackupCodes       the Argon2 hashes of single-use codes
 *
 *  Surfaces:
 *    - mfaEnrolled (bool)   so the frontend knows whether to show
 *                           "Enrolled" vs "Set up" in Settings. */
export type PublicPerson = Omit<StoredPerson, 'passwordHash' | 'mfaSecret' | 'mfaBackupCodes' | 'webauthnCredentials'> & {
  /** Public-safe representation of WebAuthn credentials — just the
   *  metadata the user / admin should see (which keys are
   *  registered, when, with what label). Credential ID and public
   *  key stay server-side. */
  webauthnCredentials?: Array<{ id: string; label: string; createdAt: string; transports?: string[] }>;
  webauthnEnrolled?: boolean;
};

export function publicPerson(p: StoredPerson): PublicPerson {
  const { passwordHash, mfaSecret, mfaBackupCodes, webauthnCredentials, ...rest } = p;
  void passwordHash; void mfaSecret; void mfaBackupCodes;
  return {
    ...rest,
    webauthnEnrolled: (webauthnCredentials?.length || 0) > 0,
    ...(webauthnCredentials?.length
      ? { webauthnCredentials: webauthnCredentials.map((c) => ({ id: c.id, label: c.label, createdAt: c.createdAt, transports: c.transports })) }
      : {}),
  };
}

// ── Org access resolution ──

export function getDescendantOrgIds(orgId: string): string[] {
  const ids: string[] = [];
  const children = organizations.filter((o) => o.parentId === orgId);
  for (const child of children) {
    ids.push(child.id);
    ids.push(...getDescendantOrgIds(child.id));
  }
  return ids;
}

function getAncestorOrgs(orgId: string, levels: string[]): string[] {
  const ids: string[] = [];
  let current = organizations.find((o) => o.id === orgId);
  while (current?.parentId) {
    const parent = organizations.find((o) => o.id === current!.parentId);
    if (!parent) break;
    if (levels.includes(parent.type)) ids.push(parent.id);
    current = parent;
  }
  return ids;
}

const WORKING_LEVELS = ['company', 'division'];

export function computeAccessibleOrgs(person: StoredPerson): Array<{ id: string; name: string; type: string; parentId: string | null }> {
  const allWorkingOrgs = organizations.filter((o) => WORKING_LEVELS.includes(o.type));

  // SUPER_ADMIN: everything
  if (person.role === 'SUPER_ADMIN') {
    return allWorkingOrgs.map((o) => ({ id: o.id, name: o.name, type: o.type, parentId: o.parentId ?? null }));
  }

  const computed = new Set<string>();

  // Process each assigned org
  for (const assignedOrgId of person.orgIds) {
    const assignedOrg = organizations.find((o) => o.id === assignedOrgId);
    if (!assignedOrg) continue;

    if (assignedOrg.type === 'company') {
      computed.add(assignedOrg.id);
      if (person.role === 'ORG_ADMIN') {
        for (const did of getDescendantOrgIds(assignedOrg.id)) {
          const d = organizations.find((o) => o.id === did);
          if (d && WORKING_LEVELS.includes(d.type)) computed.add(d.id);
        }
      } else {
        const childDivisions = organizations.filter((o) => o.parentId === assignedOrg.id && o.type === 'division');
        for (const div of childDivisions) computed.add(div.id);
      }
    } else if (assignedOrg.type === 'division') {
      computed.add(assignedOrg.id);
      if (person.role === 'ORG_ADMIN') {
        for (const did of getDescendantOrgIds(assignedOrg.id)) {
          const d = organizations.find((o) => o.id === did);
          if (d && WORKING_LEVELS.includes(d.type)) computed.add(d.id);
        }
      }
    } else {
      // Department/team/unit: find parent division or company
      for (const aid of getAncestorOrgs(assignedOrg.id, WORKING_LEVELS)) computed.add(aid);
    }
  }

  // Add explicit grants
  for (const grantId of person.accessibleOrgIds) {
    const org = organizations.find((o) => o.id === grantId);
    if (org && WORKING_LEVELS.includes(org.type)) computed.add(grantId);
  }

  // Deduplicate by org ID (Set guarantees uniqueness) and by name
  // in case the same org appears under different IDs
  const seen = new Set<string>();
  return Array.from(computed)
    .map((id) => {
      const org = organizations.find((o) => o.id === id);
      return org ? { id: org.id, name: org.name, type: org.type, parentId: org.parentId ?? null } : null;
    })
    .filter((o): o is { id: string; name: string; type: string; parentId: string | null } => {
      if (!o) return false;
      const key = `${o.name.toLowerCase()}|${o.type}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
}

/**
 * Returns the full set of org IDs the authenticated user is allowed to see,
 * or `null` when the user has unrestricted access (SUPER_ADMIN, or a user
 * with no matching people record — the dev fallback).
 *
 * The visible set is derived from `computeAccessibleOrgs` and then expanded
 * to include every descendant (of any org type) under each accessible
 * working-level org. This ensures a user scoped to, e.g., "Newport News
 * Shipbuilding" cannot see sibling divisions or other unrelated companies,
 * but can still see the departments/teams/units beneath NNS.
 */
export function getVisibleOrgIds(
  user: { email?: string; role?: string } | undefined | null,
): Set<string> | null {
  if (!user) return null;
  if (user.role === 'SUPER_ADMIN') return null;

  const person = people.find(
    (p) => p.email.toLowerCase() === (user.email || '').toLowerCase(),
  );
  // No matching people record — dev fallback, unrestricted.
  if (!person) return null;
  if (person.role === 'SUPER_ADMIN') return null;

  const visible = new Set<string>();
  for (const o of computeAccessibleOrgs(person)) {
    visible.add(o.id);
    for (const descId of getDescendantOrgIds(o.id)) {
      visible.add(descId);
    }
  }
  return visible;
}

/**
 * Returns true if the user is allowed to access the given org.
 * An unrestricted user (SUPER_ADMIN / dev fallback) always passes.
 */
export function canAccessOrg(
  user: { email?: string; role?: string } | undefined | null,
  orgId: string,
): boolean {
  const visible = getVisibleOrgIds(user);
  if (visible === null) return true;
  return visible.has(orgId);
}

export const people: StoredPerson[] = loadStore<StoredPerson>('people');

// Migration: PROCESS_OWNER and DATA_STEWARD were legacy app-roles that
// conflated platform permissions with governance accountability. They've
// been replaced by the DAMA role model. Migrate anyone still carrying
// the old values to EDITOR (closest equivalent permission set).
const LEGACY_ROLES = new Set(['PROCESS_OWNER', 'DATA_STEWARD']);
let migrated = 0;
for (const p of people) {
  if (LEGACY_ROLES.has(p.role)) {
    p.role = 'EDITOR';
    migrated++;
  }
}
if (migrated > 0) {
  saveStore('people', people);
  logger.info({ migrated }, 'Migrated legacy PROCESS_OWNER/DATA_STEWARD roles to EDITOR');
}

// Backfill skillIds on legacy records that lack the field
let skillBackfilled = 0;
for (const p of people) {
  if (!Array.isArray(p.skillIds)) {
    (p as any).skillIds = [];
    skillBackfilled++;
  }
}
if (skillBackfilled > 0) {
  saveStore('people', people);
  logger.info({ skillBackfilled }, 'Backfilled skillIds on existing people');
}

const router = Router();

/** DELETE /api/v1/people/all — delete all people */
router.delete('/all', (_req: Request, res: Response) => {
  const count = people.length;
  people.splice(0, people.length);
  saveStore('people', people);
  logger.info({ count }, 'Deleted all people');
  res.json({ success: true, deleted: count });
});

/** GET /api/v1/people
 *  Query params:
 *    orgId             scope to a specific org
 *    includeInactive   when "true", include soft-deleted records.
 *                      Defaults to false so the standard People page
 *                      stays clean. Admin views explicitly opt in. */
router.get('/', (req: Request, res: Response) => {
  const { orgId, includeInactive } = req.query;
  const includeDeactivated = String(includeInactive) === 'true';
  let filtered = orgId ? people.filter((p) => p.orgIds.includes(orgId as string)) : people;
  if (!includeDeactivated) filtered = filtered.filter(isActive);
  // Build "Root / Parent / Child" for a single org id by walking up
  // parentId. Cached per request via the closure so a person assigned
  // to many siblings doesn't re-walk the same ancestry repeatedly.
  const pathCache = new Map<string, string>();
  const orgPathFor = (oid: string): string | null => {
    if (pathCache.has(oid)) return pathCache.get(oid)!;
    const segments: string[] = [];
    let current = organizations.find((o) => o.id === oid);
    if (!current) return null;
    const seen = new Set<string>();
    while (current && !seen.has(current.id)) {
      seen.add(current.id);
      segments.unshift(current.name);
      current = current.parentId ? organizations.find((o) => o.id === current!.parentId) : undefined;
    }
    const joined = segments.join(' / ');
    pathCache.set(oid, joined);
    return joined;
  };
  // Enrich with both resolved org names (legacy callers) and the full
  // ancestor path so dropdowns can show "Name — Title · Root / Dept".
  // Credential fields are stripped via publicPerson() before enrichment
  // so a password hash never reaches a response payload.
  const enriched = filtered.map((p) => ({
    ...publicPerson(p),
    orgNames: p.orgIds
      .map((oid) => organizations.find((o) => o.id === oid)?.name)
      .filter((n): n is string => !!n),
    orgPaths: p.orgIds
      .map(orgPathFor)
      .filter((s): s is string => !!s),
  }));
  res.json({ success: true, data: enriched, roles: ROLES });
});

/** GET /api/v1/people/:id/360 — full 360 view of a person */
router.get('/:id/360', (req: Request, res: Response) => {
  const person = people.find((p) => p.id === req.params.id);
  if (!person) { res.status(404).json({ success: false, error: 'Person not found' }); return; }

  // Org assignments with resolved names
  const orgAssignments = person.orgIds
    .map((oid) => organizations.find((o) => o.id === oid))
    .filter(Boolean)
    .map((o) => ({ id: o!.id, name: o!.name, type: o!.type }));

  // DAMA roles
  const personDamaRoles = damaRoles
    .filter((r) => r.personId === person.id)
    .map((r) => {
      let scopeName = r.scopeId;
      if (r.scopeType === 'ORG') {
        const org = organizations.find((o) => o.id === r.scopeId);
        if (org) scopeName = org.name;
      }
      return { ...r, scopeName };
    });

  // Governance group memberships
  const personGroups = governanceGroups
    .filter((g) => g.members.some((m) => m.personId === person.id))
    .map((g) => {
      const membership = g.members.find((m) => m.personId === person.id)!;
      return { groupId: g.id, groupName: g.name, groupType: g.type, groupRole: membership.groupRole, since: membership.since };
    });

  // Process nodes owned
  const ownedProcessNodes = processNodes
    .filter((n) => n.ownerId === person.id)
    .map((n) => ({ id: n.id, name: n.name, level: n.level, status: n.status }));

  // Data assets owned or stewarded
  const ownedDataAssets = dataAssets
    .filter((a) => a.owner === person.id || a.owner === person.name)
    .map((a) => ({ id: a.id, name: a.name, governanceTier: a.governanceTier, relation: 'owner' as const }));
  const stewardedDataAssets = dataAssets
    .filter((a) => (a.stewardIds || []).includes(person.id) && a.owner !== person.id)
    .map((a) => ({ id: a.id, name: a.name, governanceTier: a.governanceTier, relation: 'steward' as const }));

  // Governance groups scoped to the person's orgs — deduplicated by
  // name+type to avoid showing multiple "Data Governance Council" entries
  // that may exist if templates were generated more than once.
  const personOrgSet = new Set(person.orgIds || []);
  const orgScopedGroups = governanceGroups.filter((g) => personOrgSet.size === 0 || personOrgSet.has(g.orgId));
  const seenGroupKeys = new Set<string>();
  const allGroups = orgScopedGroups
    .filter((g) => {
      const key = `${g.name.toLowerCase()}|${g.type}`;
      if (seenGroupKeys.has(key)) return false;
      seenGroupKeys.add(key);
      return true;
    })
    .map((g) => ({ id: g.id, name: g.name, type: g.type }));

  // All data domains (for checkbox UI) — scoped to person's orgs
  const allDomains = dataDomains
    .filter((d) => personOrgSet.size === 0 || personOrgSet.has(d.orgId))
    .map((d) => ({ id: d.id, name: d.name, ownerId: d.ownerId, stewardIds: d.stewardIds }));

  // All DAMA role types
  const allDamaRoleTypes = [...DAMA_ROLE_TYPES];

  res.json({
    success: true,
    data: {
      // publicPerson strips passwordHash / mfaSecret / mfaBackupCodes
      // but keeps the mfaEnrolled flag + the active flag — both
      // surfaced on the detail page's Security panel.
      person: publicPerson(person),
      orgAssignments,
      damaRoles: personDamaRoles,
      governanceGroups: personGroups,
      ownedProcessNodes,
      dataAssets: [...ownedDataAssets, ...stewardedDataAssets],
      allGroups,
      allDomains,
      allDamaRoleTypes,
    },
  });
});

/** GET /api/v1/people/:id */
router.get('/:id', (req: Request, res: Response) => {
  const person = people.find((p) => p.id === req.params.id);
  if (!person) { res.status(404).json({ success: false, error: 'Person not found' }); return; }
  res.json({ success: true, data: publicPerson(person) });
});

/** POST /api/v1/people */
router.post('/', (req: Request, res: Response) => {
  const { orgIds, orgId, name, email, role, title, jobRole, accessibleOrgIds, skillIds } = req.body;
  if (!name) { res.status(400).json({ success: false, error: 'Name is required' }); return; }
  // Support both orgIds (array) and orgId (single, backward compat)
  const assignedOrgIds: string[] = orgIds || (orgId ? [orgId] : []);
  if (assignedOrgIds.length === 0) { res.status(400).json({ success: false, error: 'At least one organization is required' }); return; }
  // Prevent duplicate emails
  if (email && people.find((p) => p.email.toLowerCase() === email.toLowerCase())) {
    res.status(409).json({ success: false, error: `A person with email "${email}" already exists.` });
    return;
  }
  for (const oid of assignedOrgIds) {
    const org = organizations.find((o) => o.id === oid);
    if (!org) { res.status(400).json({ success: false, error: `Organization "${oid}" not found.` }); return; }
  }
  const now = new Date().toISOString();
  const person: StoredPerson = {
    id: uuid(), orgIds: assignedOrgIds, name,
    email: email || '', role: role || 'VIEWER',
    title: title || '',
    ...(jobRole ? { jobRole } : {}),
    accessibleOrgIds: accessibleOrgIds || [],
    skillIds: Array.isArray(skillIds) ? skillIds : [],
    createdAt: now, updatedAt: now,
  };
  people.push(person);
  saveStore('people', people);
  res.status(201).json({ success: true, data: publicPerson(person) });
});

/** PUT /api/v1/people/:id */
router.put('/:id', (req: Request, res: Response) => {
  const person = people.find((p) => p.id === req.params.id);
  if (!person) { res.status(404).json({ success: false, error: 'Person not found' }); return; }
  const { name, email, role, title, jobRole, orgIds, orgId, accessibleOrgIds, skillIds } = req.body;
  if (name !== undefined) person.name = name;
  if (email !== undefined) person.email = email;
  if (role !== undefined) person.role = role;
  if (title !== undefined) person.title = title;
  if (jobRole !== undefined) person.jobRole = jobRole || undefined;
  if (accessibleOrgIds !== undefined) person.accessibleOrgIds = accessibleOrgIds;
  if (skillIds !== undefined) person.skillIds = Array.isArray(skillIds) ? skillIds : [];
  // Support both orgIds (array) and orgId (single, backward compat)
  const newOrgIds = orgIds || (orgId ? [orgId] : undefined);
  if (newOrgIds !== undefined) {
    for (const oid of newOrgIds) {
      const org = organizations.find((o) => o.id === oid);
      if (!org) { res.status(400).json({ success: false, error: `Organization "${oid}" not found.` }); return; }
    }
    person.orgIds = newOrgIds;
  }
  person.updatedAt = new Date().toISOString();
  saveStore('people', people);
  res.json({ success: true, data: publicPerson(person) });
});

/** GET /api/v1/people/:id/impact — preview what would be affected by deleting this person */
router.get('/:id/impact', (req: Request, res: Response) => {
  const id = req.params.id as string;
  const person = people.find((p) => p.id === id);
  if (!person) { res.status(404).json({ success: false, error: 'Person not found' }); return; }

  const ownedProcesses = processNodes.filter((n) => n.ownerId === id).length;
  const govGroups = governanceGroups.filter((g) => g.members.some((m) => m.personId === id)).length;
  const damaRoleCount = damaRoles.filter((r) => r.personId === id).length;
  const domainOwner = dataDomains.filter((d) => d.ownerId === id).length;
  const domainSteward = dataDomains.filter((d) => d.stewardIds.includes(id)).length;

  res.json({
    success: true,
    data: { ownedProcesses, governanceGroups: govGroups, damaRoles: damaRoleCount, domainOwner, domainSteward },
  });
});

/** DELETE /api/v1/people/:id */
router.delete('/:id', (req: Request, res: Response) => {
  const idx = people.findIndex((p) => p.id === req.params.id);
  if (idx === -1) { res.status(404).json({ success: false, error: 'Person not found' }); return; }
  people.splice(idx, 1);
  saveStore('people', people);
  res.status(204).send();
});

/** POST /api/v1/people/:id/deactivate
 *  Soft-delete. The person stays in the store (preserves audit trail,
 *  authored comments, role-assignment history) but can't sign in and
 *  doesn't appear in the default People list. Reverse with the
 *  /reactivate endpoint below. */
router.post('/:id/deactivate', (req: Request, res: Response) => {
  const person = people.find((p) => p.id === req.params.id);
  if (!person) { res.status(404).json({ success: false, error: 'Person not found' }); return; }
  if (person.active === false) {
    res.json({ success: true, data: publicPerson(person), message: 'Already deactivated' });
    return;
  }
  person.active = false;
  person.deactivatedAt = new Date().toISOString();
  person.updatedAt = person.deactivatedAt;
  saveStore('people', people);
  res.json({ success: true, data: publicPerson(person) });
});

/** POST /api/v1/people/:id/reactivate */
router.post('/:id/reactivate', (req: Request, res: Response) => {
  const person = people.find((p) => p.id === req.params.id);
  if (!person) { res.status(404).json({ success: false, error: 'Person not found' }); return; }
  if (person.active !== false) {
    res.json({ success: true, data: publicPerson(person), message: 'Already active' });
    return;
  }
  person.active = true;
  person.deactivatedAt = undefined;
  person.updatedAt = new Date().toISOString();
  saveStore('people', people);
  res.json({ success: true, data: publicPerson(person) });
});

/**
 * POST /api/v1/people/import
 * Import people from CSV or JSON. orgId is required as a fallback —
 * rows that include their own Org (CSV) or orgPath (JSON) override
 * it, so a single-file enterprise-wide round-trip preserves which
 * org each person belongs to. Org values can be either a full path
 * ("Tidewater Utilities > Tidewater Electric > Power Generation")
 * or a single name; single names are resolved as long as they're
 * unambiguous (one matching org).
 *
 * JSON: { orgId: string, people: [{ name, email?, role?, title?, orgPath? }, ...] }
 * CSV:  { orgId: string, csv: "Name,Email,Role,Title,Org\nJohn,john@co.com,VIEWER,Manager,Tidewater Utilities > Tidewater Electric" }
 *
 * Backward-compatible: 4-column CSVs without an Org column still
 * work — every row falls back to the dialog's orgId.
 */
router.post('/import', (req: Request, res: Response) => {
  try {
    const { orgId, people: peopleList, csv } = req.body;

    if (!orgId) {
      res.status(400).json({ success: false, error: 'Organization level is required for import' });
      return;
    }
    const org = organizations.find((o) => o.id === orgId);
    if (!org) {
      res.status(400).json({ success: false, error: 'Selected organization level does not exist' });
      return;
    }

    let rows: Array<{ name: string; email?: string; role?: string; title?: string; orgPath?: string }> = [];

    if (csv && typeof csv === 'string') {
      const parsed = parseCsv(csv);
      if (parsed.length === 0) {
        res.status(400).json({ success: false, error: 'CSV appears to be empty' });
        return;
      }
      const header = parsed[0].map((h) => h.trim().toLowerCase());
      const nameIdx = header.indexOf('name');
      const emailIdx = header.indexOf('email');
      const roleIdx = header.indexOf('role');
      const titleIdx = header.indexOf('title');
      // "Org" column is optional. When absent, every row falls back
      // to the dialog's orgId, matching the original behaviour.
      const orgIdx = header.indexOf('org');

      if (nameIdx === -1) {
        res.status(400).json({ success: false, error: 'CSV must have a "Name" column' });
        return;
      }

      for (let i = 1; i < parsed.length; i++) {
        const cols = parsed[i].map((c) => c.trim());
        if (!cols[nameIdx]) continue;
        rows.push({
          name: cols[nameIdx],
          email: emailIdx >= 0 ? cols[emailIdx] : undefined,
          role: roleIdx >= 0 ? cols[roleIdx] : undefined,
          title: titleIdx >= 0 ? cols[titleIdx] : undefined,
          orgPath: orgIdx >= 0 ? cols[orgIdx] : undefined,
        });
      }
    } else if (Array.isArray(peopleList)) {
      rows = peopleList;
    } else {
      res.status(400).json({ success: false, error: 'Provide "people" array or "csv" string' });
      return;
    }

    if (rows.length === 0) {
      res.status(400).json({ success: false, error: 'No people to import' });
      return;
    }

    // Resolve a row's Org column value to an actual org id. Accepts
    // a full path ("Parent > Child > Grandchild") or a single name.
    // Names are matched case-insensitively. Paths walk the tree
    // from the root down. Returns the fallback orgId on miss and
    // records a warning so the response can tell the user which
    // rows landed at the default.
    const warnings: string[] = [];
    const resolveOrgForRow = (raw: string | undefined, rowLabel: string): string => {
      if (!raw || !raw.trim()) return orgId;
      const path = raw.trim();
      const lc = (s: string) => s.toLowerCase();

      if (path.includes('>')) {
        const segments = path.split('>').map((s) => s.trim()).filter(Boolean);
        let parentId: string | null = null;
        let current: typeof organizations[number] | undefined;
        for (const seg of segments) {
          current = organizations.find((o) => o.parentId === parentId && lc(o.name) === lc(seg));
          if (!current) {
            warnings.push(`"${rowLabel}": no org matching path "${path}" — fell back to ${org.name}`);
            return orgId;
          }
          parentId = current.id;
        }
        return current!.id;
      }

      // Single-name shortcut. Unambiguous match required; if two orgs
      // share the name (e.g. two "Customer Service" departments) we
      // refuse to guess and fall back.
      const matches = organizations.filter((o) => lc(o.name) === lc(path));
      if (matches.length === 1) return matches[0].id;
      if (matches.length === 0) {
        warnings.push(`"${rowLabel}": no org named "${path}" — fell back to ${org.name}`);
      } else {
        warnings.push(`"${rowLabel}": "${path}" is ambiguous (${matches.length} matches) — fell back to ${org.name}; use a full path to disambiguate`);
      }
      return orgId;
    };

    const validRoles = ROLES as readonly string[];
    const created: StoredPerson[] = [];
    const skipped: string[] = [];
    const now = new Date().toISOString();

    for (const row of rows) {
      if (!row.name) continue;
      // Skip duplicates by email
      if (row.email) {
        const existing = people.find((p) => p.email.toLowerCase() === row.email!.toLowerCase());
        if (existing) {
          skipped.push(row.email);
          continue;
        }
      }
      const role = row.role && validRoles.includes(row.role.toUpperCase()) ? row.role.toUpperCase() : 'VIEWER';
      const rowOrgId = resolveOrgForRow(row.orgPath, row.email || row.name);
      const person: StoredPerson = {
        id: uuid(), orgIds: [rowOrgId], name: row.name,
        email: row.email || '', role,
        title: row.title || '',
        accessibleOrgIds: [],
        skillIds: [],
        createdAt: now, updatedAt: now,
      };
      people.push(person);
      created.push(person);
    }

    saveStore('people', people);
    logger.info({ created: created.length, skipped: skipped.length, warnings: warnings.length, defaultOrg: org.name }, 'Imported people');
    const parts: string[] = [`Imported ${created.length}`];
    if (skipped.length > 0) parts.push(`skipped ${skipped.length} duplicate${skipped.length === 1 ? '' : 's'}`);
    if (warnings.length > 0) parts.push(`${warnings.length} fell back to ${org.name}`);
    res.status(201).json({
      success: true,
      data: created.map(publicPerson),
      skipped: skipped.length,
      skippedEmails: skipped,
      warnings,
      message: parts.join(', '),
    });
  } catch (err) {
    logger.error({ err }, 'People import failed');
    res.status(500).json({ success: false, error: 'Import failed' });
  }
});

export default router;
