{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "procela.fullname" . }}-secrets
  labels:
    {{- include "procela.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "procela.databaseUrl" . | quote }}
  {{- with .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.jwtPrivateKey }}
  JWT_PRIVATE_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.jwtPublicKey }}
  JWT_PUBLIC_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.mfaEncryptionKey }}
  MFA_ENCRYPTION_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.samlIdpCert }}
  SAML_IDP_CERT: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.smtpPass }}
  SMTP_PASS: {{ . | quote }}
  {{- end }}
{{- end }}
