#!/usr/bin/env node
// Demo connector bootstrap.
//
// Pairs a REAL edge connector with a running Procela backend (via the normal
// pair/start → pair/claim handshake, as an admin) and renders a connector.yaml
// pointed at the demo source database. Used both for local verification and as
// the one-command Docker demo's init step, so the container that follows has a
// valid token and config with no human in the loop.
//
// Env:
//   PROCELA_URL        backend API base (default http://backend:3001/api/v1)
//   ADMIN_EMAIL        admin to pair as (dev login is passwordless)
//   SOURCE_DSN         Postgres DSN of the demo SOURCE db (both schemas live here)
//   CONNECTOR_NAME     display name (default "Demo Edge Connector")
//   OUT                path to write connector.yaml (default ./connector.yaml)
//   SCAN_SECONDS       scan cadence (default 30 — fast so the demo shows activity)
//   HEARTBEAT_SECONDS  heartbeat cadence (default 15)

const PROCELA_URL = process.env.PROCELA_URL || 'http://backend:3001/api/v1';
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@tidewater-utilities.com';
const SOURCE_DSN = process.env.SOURCE_DSN || 'postgres://postgres@source-db:5432/source_demo';
const CONNECTOR_NAME = process.env.CONNECTOR_NAME || 'Demo Edge Connector';
const OUT = process.env.OUT || 'connector.yaml';
const SCAN_SECONDS = process.env.SCAN_SECONDS || '30';
const HEARTBEAT_SECONDS = process.env.HEARTBEAT_SECONDS || '15';

import { writeFileSync } from 'node:fs';

async function jsonFetch(path, opts = {}) {
  const res = await fetch(PROCELA_URL + path, {
    ...opts,
    headers: { 'Content-Type': 'application/json', ...(opts.headers || {}) },
  });
  const body = await res.json().catch(() => ({}));
  if (!res.ok || body.success === false) {
    throw new Error(`${opts.method || 'GET'} ${path} → ${res.status} ${JSON.stringify(body)}`);
  }
  return body.data;
}

async function waitForBackend(tries = 60) {
  for (let i = 0; i < tries; i++) {
    try {
      const res = await fetch(PROCELA_URL + '/health');
      if (res.ok) return;
    } catch { /* not up yet */ }
    await new Promise((r) => setTimeout(r, 2000));
  }
  throw new Error(`backend never became healthy at ${PROCELA_URL}`);
}

function renderConfig(token) {
  // One source over the demo database, scanning BOTH schemas (utility +
  // shipbuilder). They live in one physical DB, so a single source is correct —
  // and it lets DQ rules resolve to this source unambiguously (a rule with no
  // systemId maps to the sole source). The password (if any) stays on-prem;
  // here the demo DB trusts the local user so no secret is needed.
  return `# Generated by docker/demo/bootstrap.mjs — do not edit by hand.
procelaUrl: ${PROCELA_URL}
token: "${token}"
heartbeatSeconds: ${HEARTBEAT_SECONDS}
scanSeconds: ${SCAN_SECONDS}
sources:
  - type: postgres
    name: demo-source
    connectionString: ${SOURCE_DSN}
    schemas:
      - utility
      - shipbuilder
`;
}

async function main() {
  console.log(`[bootstrap] waiting for backend at ${PROCELA_URL} …`);
  await waitForBackend();

  console.log(`[bootstrap] logging in as ${ADMIN_EMAIL}`);
  const login = await jsonFetch('/auth/login', {
    method: 'POST', body: JSON.stringify({ email: ADMIN_EMAIL }),
  });
  const adminToken = login.accessToken;

  console.log(`[bootstrap] pair/start "${CONNECTOR_NAME}"`);
  const started = await jsonFetch('/connectors/pair/start', {
    method: 'POST',
    headers: { Authorization: 'Bearer ' + adminToken },
    body: JSON.stringify({ name: CONNECTOR_NAME }),
  });

  console.log(`[bootstrap] pair/claim code ${started.pairingCode}`);
  const claimed = await jsonFetch('/connectors/pair/claim', {
    method: 'POST',
    body: JSON.stringify({ code: started.pairingCode, agentVersion: 'demo' }),
  });

  writeFileSync(OUT, renderConfig(claimed.token));
  console.log(`[bootstrap] wrote ${OUT} (connectorId ${claimed.connectorId})`);
}

main().catch((err) => { console.error('[bootstrap] FAILED:', err.message); process.exit(1); });
