import { useEffect, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { SkeletonRows } from '../components/Skeleton';
import PageHeader from '../components/PageHeader';
import ExportMenu from '../components/ExportMenu';
import DataTable, { type DataTableColumn } from '../components/DataTable';
import Modal from '../components/Modal';
import IconButton from '../components/IconButton';
import TruncatedText from '../components/TruncatedText';
import { renderNavIcon } from '../components/navIcons';
import { useSortedList } from '../hooks/useSortedList';
import type { Cell, ExportPayload } from '../lib/export';
import { exportData } from '../lib/export';
import { apiClient } from '../api/client';
import { useOrgContext } from '../stores/orgContext';
import { useToastStore } from '../stores/toastStore';
import { useBrandingStore } from '../stores/brandingStore';
import { useAuthStore } from '../stores/authStore';

interface UserReportSummary {
  id: string;
  name: string;
  description: string;
  visibility: 'private' | 'org';
  primaryEntity: string;
  columnCount: number;
  lastRunAt: string | null;
  lastRunRowCount: number | null;
  runCount: number;
  scheduleFrequency: 'off' | 'weekly';
  updatedAt: string;
}

interface RunResult {
  columns: Array<{ field: string; label: string }>;
  rows: Array<Record<string, unknown>>;
  totalMatched: number;
}

// Download formats offered in the results modal (Print is a separate action,
// so PDF is not listed here — see the decoupled Print button).
const DOWNLOAD_FORMATS = ['csv', 'xlsx', 'json', 'clipboard'] as const;

function toExportCell(v: unknown): Cell {
  if (v == null) return '';
  if (typeof v === 'boolean' || typeof v === 'number' || typeof v === 'string') return v;
  if (Array.isArray(v)) return v.join(', ');
  return String(v);
}

function timeAgo(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

// Turn an already-run result into an export payload — used by both Download
// and Print so neither re-runs the report (run and export are decoupled).
// The `logoUrl` (tenant branding) rides along in `header` so the PDF/print
// output carries the same letterhead the results modal shows on screen; the
// data-only formats (CSV/XLSX/JSON) ignore it.
function resultToPayload(
  report: UserReportSummary,
  result: RunResult,
  opts?: { logoUrl?: string; companyName?: string; userName?: string },
): ExportPayload {
  const name = report.name;
  const headers = result.columns.map((c) => c.label);
  const rows: Cell[][] = result.rows.map((row) => result.columns.map((c) => toExportCell(row[c.field])));
  const base = (name || 'report').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'report';
  const footer = [
    opts?.companyName,
    name || 'Report',
    `Generated ${new Date().toLocaleDateString()}`,
    opts?.userName ? `by ${opts.userName}` : null,
  ].filter(Boolean).join('  ·  ');
  return {
    filenameBase: base, headers, rows, sheetName: name || 'Report',
    header: { title: name || 'Report', description: report.description || undefined, logoUrl: opts?.logoUrl, companyName: opts?.companyName },
    footer,
  };
}

const badgeStyle = (bg: string, color: string): React.CSSProperties => ({
  marginLeft: 8, fontSize: 10, fontWeight: 600, padding: '1px 6px', borderRadius: 3, background: bg, color, whiteSpace: 'nowrap',
});

// ── User Reports — saved Report Builder definitions ────────────────────────

function UserReportsTab() {
  const navigate = useNavigate();
  const { activeOrgId } = useOrgContext();
  const addToast = useToastStore((s) => s.addToast);
  // Brand logo + company name for the report letterhead (shown in the results
  // modal and the printed/PDF output), and the signed-in user for the footer's
  // "generated by" provenance.
  const logoUrl = useBrandingStore((s) => s.branding.logoUrl);
  const companyName = useBrandingStore((s) => s.branding.companyName);
  const userName = useAuthStore((s) => s.user?.name);
  const [reports, setReports] = useState<UserReportSummary[] | null>(null);
  const [runningId, setRunningId] = useState<string | null>(null);
  // The produced report shown in the results modal — the result of a Run.
  // Download/Print in the modal act on this cached data, never re-running.
  const [result, setResult] = useState<{ report: UserReportSummary; data: RunResult } | null>(null);

  const load = useCallback(() => {
    if (!activeOrgId) { setReports([]); return; }
    apiClient.get<{ success: boolean; data: UserReportSummary[] }>(`/reports?orgId=${activeOrgId}`)
      .then((r) => setReports(r.data || []))
      .catch(() => setReports([]));
  }, [activeOrgId]);

  useEffect(() => { load(); }, [load]);

  const remove = async (id: string, name: string) => {
    if (!confirm(`Delete "${name}"? This can't be undone.`)) return;
    try {
      await apiClient.delete(`/reports/${id}`);
      addToast('success', `Deleted "${name}".`);
      load();
    } catch {
      addToast('error', 'Delete failed.');
    }
  };

  // Run (execute) a report: fetch its rows and open the results modal. Running
  // records a run server-side, so refresh the list for the updated "last run".
  const runReport = async (r: UserReportSummary) => {
    setRunningId(r.id);
    try {
      const res = await apiClient.post<{ success: boolean; data: RunResult }>(`/reports/${r.id}/run`, {});
      load(); // refresh run-history metadata
      setResult({ report: r, data: res.data });
    } catch (err) {
      addToast('error', `Run failed: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setRunningId(null);
    }
  };

  const printResult = () => {
    if (!result) return;
    if (result.data.rows.length === 0) { addToast('info', 'No rows to print.'); return; }
    exportData('pdf', resultToPayload(result.report, result.data, { logoUrl, companyName, userName })).catch((err) =>
      addToast('error', `Print failed: ${err instanceof Error ? err.message : String(err)}`));
  };

  const columns: DataTableColumn<UserReportSummary>[] = [
    {
      key: 'name', header: 'Report', sortable: true,
      render: (r) => (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 }}>
          <span style={{ flexShrink: 0, display: 'inline-flex', color: 'var(--color-text-muted)' }}>{renderNavIcon('/reports', { size: 16 })}</span>
          <TruncatedText text={r.name} style={{ fontWeight: 600 }} />
          {r.visibility === 'private' && <span style={badgeStyle('var(--color-bg)', 'var(--color-text-muted)')}>PRIVATE</span>}
        </div>
      ),
    },
    {
      key: 'description', header: 'Description',
      render: (r) => r.description
        ? <TruncatedText text={r.description} style={{ color: 'var(--color-text-secondary)' }} />
        : <span style={{ color: 'var(--color-text-muted)' }}>—</span>,
    },
    {
      key: 'source', header: 'Source', sortable: true, width: 150,
      render: (r) => <span style={{ color: 'var(--color-text-secondary)' }}>{r.primaryEntity}</span>,
    },
    {
      key: 'columns', header: 'Columns', align: 'center', width: 90,
      render: (r) => <span style={{ color: 'var(--color-text-secondary)' }}>{r.columnCount}</span>,
    },
    {
      key: 'lastRun', header: 'Last run', sortable: true, width: 200,
      render: (r) => (
        <span style={{ color: 'var(--color-text-secondary)', whiteSpace: 'nowrap' }}>
          {r.lastRunAt
            ? <>{timeAgo(r.lastRunAt)}{r.lastRunRowCount != null ? ` · ${r.lastRunRowCount.toLocaleString()} ${r.lastRunRowCount === 1 ? 'row' : 'rows'}` : ''}</>
            : <span style={{ color: 'var(--color-text-muted)' }}>Never run</span>}
          {r.scheduleFrequency === 'weekly' && <span style={badgeStyle('var(--color-primary-light)', 'var(--color-primary)')}>WEEKLY</span>}
        </span>
      ),
    },
    {
      key: 'actions', header: 'Actions', align: 'center', width: 130,
      render: (r) => (
        <div style={{ display: 'inline-flex', gap: 4, alignItems: 'center', justifyContent: 'center', flexWrap: 'nowrap' }}>
          <IconButton size="sm" icon="play" label={runningId === r.id ? 'Running…' : 'Run report'} disabled={runningId === r.id} onClick={() => runReport(r)} />
          <IconButton size="sm" icon="edit" label="Edit report" onClick={() => navigate(`/reports/builder/${r.id}`)} />
          <IconButton size="sm" icon="trash" label="Delete report" variant="danger" onClick={() => remove(r.id, r.name)} />
        </div>
      ),
    },
  ];

  const { sorted, sortKey, sortDir, toggleSort } = useSortedList<UserReportSummary>(
    reports || [],
    {
      name: (a, b) => a.name.localeCompare(b.name),
      source: (a, b) => a.primaryEntity.localeCompare(b.primaryEntity),
      lastRun: (a, b) => (a.lastRunAt ? new Date(a.lastRunAt).getTime() : 0) - (b.lastRunAt ? new Date(b.lastRunAt).getTime() : 0),
    },
    'name',
  );

  return (
    <>
      {reports === null ? (
        <SkeletonRows rows={4} columnWidths={[220, null, 120]} />
      ) : reports.length === 0 ? (
        <div style={{ fontSize: 13, color: 'var(--color-text-muted)', padding: '24px 0', textAlign: 'center' }}>
          No reports yet. Click <strong>+ New report</strong> to build one.
        </div>
      ) : (
        <DataTable
          rows={sorted}
          columns={columns}
          rowKey={(r) => r.id}
          sort={{ sortKey, sortDir, onSort: toggleSort }}
          emptyMessage="No reports match."
        />
      )}

      {result && (
        <Modal
          open
          onClose={() => setResult(null)}
          size="lg"
          kicker={result.report.primaryEntity}
          // The report name lives in the branded letterhead inside the body, so
          // the window chrome stays neutral (and keeps the name as its
          // accessible label) rather than printing the name twice.
          title="Report results"
          ariaLabel={result.report.name}
          subtitle={`${result.data.totalMatched.toLocaleString()} ${result.data.totalMatched === 1 ? 'row' : 'rows'} matched${result.data.totalMatched > result.data.rows.length ? ` · showing first ${result.data.rows.length.toLocaleString()}` : ''}`}
          actions={
            <>
              <IconButton size="sm" icon="printer" label="Print" onClick={printResult} />
              <ExportMenu label="Download" formats={[...DOWNLOAD_FORMATS]} build={() => resultToPayload(result.report, result.data, { logoUrl, companyName, userName })} />
            </>
          }
        >
          {/* Report letterhead — brand logo pinned left, report name centred,
              description centred below it. Mirrors the printed/PDF header so the
              on-screen report and the export read the same. */}
          <div style={{ position: 'relative', textAlign: 'center', paddingBottom: 12, marginBottom: 14, borderBottom: '2px solid var(--color-border)', minHeight: 40 }}>
            {logoUrl && <img src={logoUrl} alt="" style={{ position: 'absolute', left: 0, top: 0, maxHeight: 40, maxWidth: 160, objectFit: 'contain' }} />}
            {companyName && (
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--color-text-muted)', marginBottom: 2 }}>{companyName}</div>
            )}
            <div style={{ fontSize: 18, fontWeight: 700, color: 'var(--color-text)' }}>{result.report.name}</div>
            {result.report.description && (
              <div style={{ fontSize: 12, color: 'var(--color-text-secondary)', margin: '4px auto 0', maxWidth: '70%', lineHeight: 1.4 }}>{result.report.description}</div>
            )}
          </div>
          {result.data.rows.length === 0 ? (
            <div style={{ padding: '32px 0', textAlign: 'center', color: 'var(--color-text-muted)', fontSize: 13 }}>
              No rows match this report.
            </div>
          ) : (
            <div style={{ overflow: 'auto', maxHeight: '60vh', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
                <thead>
                  <tr>
                    {result.data.columns.map((c) => (
                      <th key={c.field} style={{ position: 'sticky', top: 0, background: 'var(--color-bg)', textAlign: 'left', fontWeight: 600, color: 'var(--color-text-muted)', padding: '8px 12px', borderBottom: '1px solid var(--color-border)', whiteSpace: 'nowrap' }}>
                        {c.label}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {result.data.rows.map((row, i) => (
                    <tr key={i} style={{ borderBottom: '1px solid var(--color-border)' }}>
                      {result.data.columns.map((c) => (
                        <td key={c.field} style={{ padding: '6px 12px', whiteSpace: 'nowrap', color: 'var(--color-text)' }}>
                          {String(toExportCell(row[c.field]))}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          {/* Provenance footer — mirrors the printed/PDF footer. */}
          <div style={{ marginTop: 12, paddingTop: 8, borderTop: '1px solid var(--color-border)', fontSize: 10, color: 'var(--color-text-muted)', textAlign: 'center' }}>
            {[companyName, result.report.name, `Generated ${new Date().toLocaleDateString()}`, userName ? `by ${userName}` : null].filter(Boolean).join('  ·  ')}
          </div>
        </Modal>
      )}
    </>
  );
}

export default function ReportsPage() {
  const navigate = useNavigate();
  // Reports is the report catalog + Builder. The Executive Report and
  // Governance Maturity Scorecard tabs were removed, so there's no tab bar.
  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle="Reports you and your org have built against the Procela data model."
        actions={<IconButton icon="plus" label="New report" variant="primary" onClick={() => navigate('/reports/builder')} />}
      />
      <UserReportsTab />
    </div>
  );
}
