import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { INDUSTRIES } from '../types';
import { apiClient } from '../api/client';
import { useOrgContext } from '../stores/orgContext';

// ── Types ──

interface TemplateActivity { name: string; description: string; }
interface TemplateProcess { name: string; description: string; purpose?: string; activities: TemplateActivity[]; subProcesses?: any[]; }
interface TemplateValueStream { name: string; description: string; purpose?: string; businessOutcome?: string; processes: TemplateProcess[]; selected: boolean; }
interface GeneratedTemplate { valueStreams: TemplateValueStream[]; }

// ── Styles ──

const card: React.CSSProperties = {
  background: 'var(--color-surface)', border: '1px solid var(--color-border)',
  borderRadius: 'var(--radius-lg)', padding: 24, boxShadow: 'var(--shadow-sm)',
};

const btnPrimary: React.CSSProperties = {
  padding: '10px 24px', background: 'var(--color-primary)', color: '#fff',
  border: 'none', borderRadius: 'var(--radius-md)', fontSize: 14, fontWeight: 500, cursor: 'pointer',
};

const btnSecondary: React.CSSProperties = {
  padding: '10px 24px', background: 'var(--color-bg)', color: 'var(--color-text)',
  border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)', fontSize: 14, fontWeight: 500, cursor: 'pointer',
};

// ── Component ──

export default function ValueStreamWizard() {
  const navigate = useNavigate();
  const { activeOrgId, activeOrgName } = useOrgContext();
  const [industry, setIndustry] = useState('');
  const [orgIndustry, setOrgIndustry] = useState('');
  const [industrySource, setIndustrySource] = useState<'own' | 'inherited' | ''>('');
  const [template, setTemplate] = useState<GeneratedTemplate | null>(null);
  const [loading, setLoading] = useState(false);
  const [applying, setApplying] = useState(false);
  const [error, setError] = useState('');
  const [expandedStreams, setExpandedStreams] = useState<Set<number>>(new Set());
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Fetch org's industry
  useEffect(() => {
    if (!activeOrgId) return;
    async function loadOrgIndustry() {
      try {
        const res = await apiClient.get<{ success: boolean; data: { industry?: string; parentId?: string | null } }>(`/organizations/${activeOrgId}`);
        const org = res.data;
        if (org?.industry) {
          setOrgIndustry(org.industry);
          setIndustry(org.industry);
          setIndustrySource('own');
        } else if (org?.parentId) {
          try {
            const parentRes = await apiClient.get<{ success: boolean; data: { industry?: string } }>(`/organizations/${org.parentId}`);
            if (parentRes.data?.industry) {
              setOrgIndustry(parentRes.data.industry);
              setIndustry(parentRes.data.industry);
              setIndustrySource('inherited');
            }
          } catch { /* */ }
        }
      } catch { /* */ }
    }
    loadOrgIndustry();
  }, [activeOrgId]);

  // Auto-generate when industry is resolved from org
  const handleGenerate = useCallback(async (ind: string) => {
    if (!ind || loading) return;
    setLoading(true);
    setError('');
    setTemplate(null);
    try {
      const res = await apiClient.post<{ success: boolean; data: { valueStreams: Omit<TemplateValueStream, 'selected'>[] } }>(
        '/ai/generate-template', { industry: ind }
      );
      if (res.data) {
        setTemplate({ valueStreams: res.data.valueStreams.map((vs) => ({ ...vs, selected: true })) });
        setExpandedStreams(new Set([0]));
      } else {
        setError('Unexpected response format. Please try again.');
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to generate. Is the API key configured?');
    } finally {
      setLoading(false);
    }
  }, [loading]);

  // Auto-generate on first load if org has industry
  useEffect(() => {
    if (orgIndustry && !template && !autoGenerated && !loading) {
      setAutoGenerated(true);
      handleGenerate(orgIndustry);
    }
  }, [orgIndustry, template, autoGenerated, loading, handleGenerate]);

  const toggleStream = (idx: number) => {
    setExpandedStreams((prev) => { const next = new Set(prev); next.has(idx) ? next.delete(idx) : next.add(idx); return next; });
  };

  const toggleStreamSelection = (idx: number) => {
    if (!template) return;
    setTemplate({ ...template, valueStreams: template.valueStreams.map((vs, i) => i === idx ? { ...vs, selected: !vs.selected } : vs) });
  };

  const selectAll = () => {
    if (!template) return;
    const allSelected = template.valueStreams.every((vs) => vs.selected);
    setTemplate({ ...template, valueStreams: template.valueStreams.map((vs) => ({ ...vs, selected: !allSelected })) });
  };

  const handleApply = async () => {
    if (!template) return;
    setApplying(true);
    setError('');
    try {
      const selectedStreams = template.valueStreams.filter((vs) => vs.selected).map(({ selected: _, ...rest }) => rest);
      await apiClient.post('/process-catalog/apply-template', { industry, valueStreams: selectedStreams, orgId: activeOrgId || undefined });
      navigate('/processes');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to apply template.');
      setApplying(false);
    }
  };

  const selectedCount = template?.valueStreams.filter((vs) => vs.selected).length ?? 0;
  const totalProcesses = template ? template.valueStreams.filter((vs) => vs.selected).reduce((sum, vs) => sum + vs.processes.length, 0) : 0;
  const totalActivities = template ? template.valueStreams.filter((vs) => vs.selected).reduce((sum, vs) => sum + vs.processes.reduce((s, p) => s + (p.activities || []).length, 0), 0) : 0;

  return (
    <div style={{ maxWidth: 900, margin: '0 auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 }}>
        <div>
          <h1 style={{ fontSize: 24, fontWeight: 600, marginBottom: 4 }}>
            {activeOrgName ? `Process Wizard — ${activeOrgName}` : 'Process Wizard'}
          </h1>
          <p style={{ fontSize: 13, color: 'var(--color-text-secondary)' }}>
            AI generates a complete process hierarchy (Value Streams → Processes → Activities) based on your industry.
          </p>
        </div>
        <button style={btnSecondary} onClick={() => navigate('/processes')}>Back to Processes</button>
      </div>

      {/* Step 1: Industry + Generate */}
      {!template && !loading && (
        <div style={card}>
          <h2 style={{ fontSize: 16, fontWeight: 600, marginBottom: 12 }}>
            {orgIndustry ? 'Generating processes...' : 'Select Industry'}
          </h2>

          {orgIndustry ? (
            <div style={{ background: 'var(--color-primary-light)', border: '1px solid var(--color-primary)', borderRadius: 'var(--radius-md)', padding: '12px 16px', marginBottom: 12 }}>
              <div style={{ fontSize: 12, color: 'var(--color-text-muted)', marginBottom: 2 }}>
                Industry {industrySource === 'inherited' ? '(from parent organization)' : '(from organization)'}
              </div>
              <div style={{ fontSize: 15, fontWeight: 600, color: 'var(--color-primary)' }}>{orgIndustry}</div>
              <button onClick={() => { setOrgIndustry(''); setIndustry(''); }} style={{ fontSize: 11, color: 'var(--color-text-muted)', background: 'none', border: 'none', cursor: 'pointer', padding: 0, marginTop: 4, textDecoration: 'underline' }}>
                Choose a different industry
              </button>
            </div>
          ) : (
            <div style={{ marginBottom: 16 }}>
              <select value={industry} onChange={(e) => setIndustry(e.target.value)}
                style={{ width: '100%', padding: '10px 12px', fontSize: 14, border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)', background: 'var(--color-surface)' }}>
                <option value="">-- Select an industry --</option>
                {INDUSTRIES.map((ind) => <option key={ind} value={ind}>{ind}</option>)}
              </select>
            </div>
          )}

          {error && <p style={{ color: 'var(--color-error)', fontSize: 13, marginBottom: 12 }}>{error}</p>}

          {!orgIndustry && (
            <button
              style={{ ...btnPrimary, opacity: !industry || loading ? 0.6 : 1 }}
              disabled={!industry || loading}
              onClick={() => handleGenerate(industry)}
            >
              {loading ? 'Generating\u2026' : 'Generate Processes'}
            </button>
          )}
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div style={{ ...card, textAlign: 'center', padding: '3rem', border: '1px solid var(--color-primary)' }}>
          <div style={{ fontSize: 32, marginBottom: 12, animation: 'procelaGenSpin 2s linear infinite' }}>{'\u2699'}</div>
          <h2 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8, color: 'var(--color-primary)' }}>Generating process hierarchy...</h2>
          <p style={{ fontSize: 13, color: 'var(--color-text-muted)' }}>
            AI is creating value streams, processes, and activities for {industry || orgIndustry}. This usually takes 10{'\u2013'}30 seconds.
          </p>
          <style>{`@keyframes procelaGenSpin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
        </div>
      )}

      {/* Step 2: Review & Apply (combined preview + confirm) */}
      {template && !loading && (
        <div style={card}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
            <div>
              <h2 style={{ fontSize: 16, fontWeight: 600 }}>Review & Apply</h2>
              <p style={{ fontSize: 12, color: 'var(--color-text-muted)' }}>
                {selectedCount} value streams, {totalProcesses} processes, {totalActivities} activities selected
              </p>
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              <button style={{ ...btnSecondary, fontSize: 12, padding: '6px 14px' }} onClick={selectAll}>
                {template.valueStreams.every((vs) => vs.selected) ? 'Deselect All' : 'Select All'}
              </button>
              <button style={{ ...btnSecondary, fontSize: 12, padding: '6px 14px' }} onClick={() => { setTemplate(null); setAutoGenerated(false); }}>
                Regenerate
              </button>
            </div>
          </div>

          {/* Value Stream List */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 20 }}>
            {template.valueStreams.map((vs, vsIdx) => {
              const isExpanded = expandedStreams.has(vsIdx);
              return (
                <div key={vsIdx} style={{
                  border: `1px solid ${vs.selected ? 'var(--color-primary)' : 'var(--color-border)'}`,
                  borderRadius: 'var(--radius-md)', overflow: 'hidden',
                  background: vs.selected ? 'var(--color-primary-light)' : 'var(--color-bg)',
                  transition: 'border-color 0.15s, background 0.15s',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', cursor: 'pointer' }}
                    onClick={() => toggleStream(vsIdx)}>
                    <input type="checkbox" checked={vs.selected} onChange={(e) => { e.stopPropagation(); toggleStreamSelection(vsIdx); }}
                      onClick={(e) => e.stopPropagation()} style={{ width: 16, height: 16, accentColor: 'var(--color-primary)' }} />
                    <span style={{ fontSize: 12, color: 'var(--color-text-muted)', userSelect: 'none' }}>{isExpanded ? '\u25BC' : '\u25B6'}</span>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontWeight: 600, fontSize: 14 }}>{vs.name}</div>
                      <div style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>{vs.description}</div>
                    </div>
                    <span style={{ fontSize: 11, color: 'var(--color-text-muted)', whiteSpace: 'nowrap' }}>
                      {vs.processes.length} processes
                    </span>
                  </div>

                  {isExpanded && (
                    <div style={{ padding: '0 14px 12px 44px' }}>
                      {(vs.purpose || vs.businessOutcome) && (
                        <div style={{ fontSize: 11, padding: '6px 10px', background: '#f8fafc', borderRadius: 4, marginBottom: 10 }}>
                          {vs.purpose && <div><span style={{ fontWeight: 600, color: 'var(--color-text-muted)' }}>Purpose:</span> {vs.purpose}</div>}
                          {vs.businessOutcome && <div><span style={{ fontWeight: 600, color: 'var(--color-text-muted)' }}>Business Outcome:</span> {vs.businessOutcome}</div>}
                        </div>
                      )}
                      {vs.processes.map((proc, pIdx) => (
                        <div key={pIdx} style={{ marginBottom: 8 }}>
                          <div style={{ fontWeight: 500, fontSize: 13, marginBottom: 2 }}>{proc.name}</div>
                          <div style={{ fontSize: 11, color: 'var(--color-text-muted)', marginBottom: 4 }}>{proc.description}</div>
                          {proc.purpose && (
                            <div style={{ fontSize: 10, color: 'var(--color-text-secondary)', marginBottom: 4, fontStyle: 'italic' }}>
                              Purpose: {proc.purpose}
                            </div>
                          )}
                          {(proc.activities || []).length > 0 && (
                            <div style={{ marginLeft: 16 }}>
                              {proc.activities.map((act, aIdx) => (
                                <div key={aIdx} style={{ display: 'flex', alignItems: 'flex-start', gap: 4, marginBottom: 2 }}>
                                  <span style={{ color: '#065f46', fontSize: 9, marginTop: 2 }}>{'\u25B6'}</span>
                                  <div>
                                    <span style={{ fontSize: 11, fontWeight: 500 }}>{act.name}</span>
                                    {act.description && <span style={{ fontSize: 10, color: 'var(--color-text-muted)', marginLeft: 4 }}>— {act.description}</span>}
                                  </div>
                                </div>
                              ))}
                            </div>
                          )}
                          {(proc.subProcesses || []).map((sp: any, spIdx: number) => (
                            <div key={spIdx} style={{ marginLeft: 16, marginBottom: 4 }}>
                              <div style={{ fontWeight: 500, fontSize: 11, color: 'var(--color-text-secondary)' }}>{sp.name}</div>
                              <ul style={{ listStyle: 'disc', paddingLeft: 16, margin: 0 }}>
                                {(sp.steps || sp.activities || []).map((st: any, stIdx: number) => (
                                  <li key={stIdx} style={{ fontSize: 10, color: 'var(--color-text-muted)', lineHeight: 1.5 }}>{st.name}</li>
                                ))}
                              </ul>
                            </div>
                          ))}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {error && <p style={{ color: 'var(--color-error)', fontSize: 13, marginBottom: 12 }}>{error}</p>}

          {/* Apply */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <button style={btnSecondary} onClick={() => navigate('/processes')}>Cancel</button>
            <button
              style={{ ...btnPrimary, opacity: selectedCount === 0 || applying ? 0.6 : 1, padding: '12px 32px', fontSize: 15 }}
              disabled={selectedCount === 0 || applying}
              onClick={handleApply}
            >
              {applying ? 'Applying...' : `Apply ${selectedCount} Value Stream${selectedCount !== 1 ? 's' : ''} to Catalog`}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
